version: '3.7'
services:
  java_app:
    env_file:
      - .env
    build: ./
    #command:
    #  bash -c "chmod +x /start.sh && sh /init.sh"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    restart: on-failure
    network_mode: host
#  postgres:
#    image: postgres:latest
#    environment:
#      - POSTGRES_USER=postgres
#      - PGUSER=postgres
#      - POSTGRES_NAME=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
volumes:
  app:
